name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v2

      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 19

      - name: Install Android SDK
        run: ./.github/android-sdk.sh

      - uses: gradle/gradle-build-action@v3

      - name: Build with Gradle
        run: ./gradlew build --stacktrace
